version: 2.1
jobs:
  build:
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .
      - run:
          name: Test
          command: yarn test